export const FONTS = [
  { label: 'Default Font', value: '' },
  { label: 'Source Han Sans', value: 'SourceHanSans' },
  { label: 'Source Han Serif', value: 'SourceHanSerif' },
  { label: 'FZ HeiTi (FangZheng Black)', value: 'FangZhengHeiTi' },
  { label: 'FZ KaiTi (FangZheng Kai)', value: 'FangZhengKaiTi' },
  { label: 'FZ SongTi (FangZheng Song)', value: 'FangZhengShuSong' },
  { label: 'FZ FangSong (FangZheng FangSong)', value: 'FangZhengFangSong' },
  { label: 'Alibaba PuHuiTi', value: 'AlibabaPuHuiTi' },
  { label: 'Zhuque FangSong', value: 'ZhuqueFangSong' },
  { label: 'LXGW WenKai', value: 'LXGWWenKai' },
  { label: 'WenDing PL KaiTi', value: 'WenDingPLKaiTi' },
  { label: 'DeYiHei', value: 'DeYiHei' },
  { label: 'MiSans', value: 'MiSans' },
  { label: 'Canger Xiaowanzi', value: 'CangerXiaowanzi' },
  { label: 'Youshe Title Black', value: 'YousheTitleBlack' },
  { label: 'Fengguang Mingrui', value: 'FengguangMingrui' },
  { label: 'Shetu Modern Square', value: 'ShetuModernSquare' },
  { label: 'Zcool Happy', value: 'ZcoolHappy' },
  { label: 'Zizhiqu Ximai', value: 'ZizhiQuXiMai' },
  { label: 'Sucai Jishi Kangkang', value: 'SucaiJishiKangkang' },
  { label: 'Sucai Jishi Cool Square', value: 'SucaiJishiCoolSquare' },
  { label: 'Tuniu Rounded', value: 'TuniuRounded' },
  { label: 'Ruizi Zhenyan', value: 'RuiziZhenyan' },
]